#Todos Service Are Running On This Port Number
server:
  port: 8091

# Configuring Spring Providing Name To The Service Configuring Database Setting Servlet Multipart To Store file
spring:
  application:
    name: todo-service
  data:
    mongodb:
      database: todosDetails
      uri: mongodb://mongodb-service:27017                            # mongodb-service
  error:
    include-message: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  rabbitmq:
    username: admin
    password: admin2017

#Registering Todos Service With Eureka Server
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

